import { THEME_COLORS } from "../styles/globalThemeTokens";

export const TEMPLATE_LIBRARY = [
  {
    id: "clean-support",
    name: "Clean Support",
    description: "Minimal layout with neutral background and green CTA.",
    brandColor: THEME_COLORS.primary,
    textColor: THEME_COLORS.textPrimary,
    backgroundColor: THEME_COLORS.bgWhite,
    title: "Support Desk",
    subtitle: "Replies in a few minutes",
    welcomeMessage: "Hi there. Tell us what you need and we will assist you.",
    position: "right",
    width: 360,
    height: 480,
  },
  {
    id: "bold-sales",
    name: "Bold Sales",
    description: "High-contrast layout for lead capture and quick engagement.",
    brandColor: THEME_COLORS.slate900,
    textColor: THEME_COLORS.textPrimary,
    backgroundColor: THEME_COLORS.bgSlate50,
    title: "Sales Concierge",
    subtitle: "Book demos and pricing instantly",
    welcomeMessage: "Welcome. Want pricing, demo, or implementation details?",
    position: "right",
    width: 380,
    height: 500,
  },
  {
    id: "night-ops",
    name: "Night Ops",
    description: "Dark support look optimized for technical or dev products.",
    brandColor: THEME_COLORS.emerald500,
    textColor: THEME_COLORS.textDark,
    backgroundColor: THEME_COLORS.slate900,
    title: "Tech Support",
    subtitle: "Fast help for production issues",
    welcomeMessage: "Share logs or issue details and we will troubleshoot.",
    position: "left",
    width: 380,
    height: 520,
  },
  {
    id: "care-clinic",
    name: "Care Clinic",
    description: "Friendly healthcare-style template with soft palette.",
    brandColor: THEME_COLORS.sky500,
    textColor: THEME_COLORS.textPrimary,
    backgroundColor: THEME_COLORS.bgSky50,
    title: "Care Assistant",
    subtitle: "Ask about appointments and support",
    welcomeMessage: "Hello. How can our care team support you today?",
    position: "right",
    width: 360,
    height: 500,
  },
  {
    id: "enterprise-hub",
    name: "Enterprise Hub",
    description: "Formal enterprise support style for B2B accounts.",
    brandColor: THEME_COLORS.slate700,
    textColor: THEME_COLORS.slate800,
    backgroundColor: THEME_COLORS.bgWhite,
    title: "Enterprise Success",
    subtitle: "Priority account support channel",
    welcomeMessage: "Welcome back. Please share your account request.",
    position: "left",
    width: 400,
    height: 520,
  },
  {
    id: "creator-mode",
    name: "Creator Mode",
    description: "Modern expressive template for creator and community brands.",
    brandColor: THEME_COLORS.pink600,
    textColor: THEME_COLORS.gray800,
    backgroundColor: THEME_COLORS.bgRose50,
    title: "Creator Support",
    subtitle: "Let us help with collabs and growth",
    welcomeMessage: "Hey creator. Tell us your goal and we will guide you.",
    position: "right",
    width: 360,
    height: 500,
  },
];
